Int 114 sdk get media
Bynder/drupal-media-bynder pull request #51
Opened 2017-02-21 11:12 UTC by jfcsantos

2017-02-27 11:14 UTC, danielsequeira requested changes

2017-02-27 11:14 UTC, danielsequeira commented on includes/MediaBynderBrowser.inc
> +        $build['form'] = drupal_get_form('media_bynder_add', $params);
why not pass $this->params directly here?

2017-02-27 11:14 UTC, danielsequeira commented on includes/media_bynder.formatters.inc
> +function media_bynder_file_formatter_info_alter(&$info)
why are some function names camel case and others with underscore?

2017-02-27 11:14 UTC, danielsequeira commented on media_bynder.module
> +        'website' => 'http://www.getbynder.com',
www.bynder.com

2017-02-28 14:56 UTC, jfcsantos commented on includes/MediaBynderBrowser.inc
> +        $build['form'] = drupal_get_form('media_bynder_add', $params);
because I didn't touch this function, old code.

2017-02-28 14:59 UTC, jfcsantos commented on includes/media_bynder.formatters.inc
> +function media_bynder_file_formatter_info_alter(&$info)
OOP PHP vs Drupal 7, the camel case ones are normally PHP classes implemented in external libraries and adhering to proper PHP coding standards. Underscore ones are Drupal 7 standards for function names

2017-02-28 14:59 UTC, jfcsantos commented on media_bynder.module
> +        'website' => 'http://www.getbynder.com',
done

2017-02-28 14:59 UTC, merged